DROP TABLE IF EXISTS comment;

CREATE TABLE comment (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    comment_text TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    toxic INTEGER NOT NULL,
    severe_toxic INTEGER NOT NULL,
    obscene INTEGER NOT NULL,
    threat INTEGER NOT NULL,
    insult INTEGER NOT NULL,
    identity_hate INTEGER NOT NULL
);